In [1]:
import graphlab
import numpy as np
from sklearn import linear_model as lm

/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
[WARNING] graphlab.product_key: Unable to write current GraphLab Create license to /home/srijit/.graphlab/config. Ensure that this user account                    

This non-commercial license of GraphLab Create for academic use is assigned to srijitcnair@hotmail.com and will expire on September 03, 2017.


[WARNING] graphlab.deploy._session: Unable to create session in specified location: '/home/srijit/.graphlab/artifacts'. Using: '/var/tmp/graphlab-srijit/25286/tmp_session_da6a98cb-ff04-4d40-94ec-25ee49c09643'


In [2]:
dtype_dict = {'bathrooms':float, 'waterfront':int, 'sqft_above':int, 'sqft_living15':float, 'grade':int, 'yr_renovated':int, 'price':float, 'bedrooms':float, 'zipcode':str, 'long':float, 'sqft_lot15':float, 'sqft_living':float, 'floors':str, 'condition':int, 'lat':float, 'date':str, 'sqft_basement':int, 'yr_built':int, 'id':str, 'sqft_lot':int, 'view':int}

train_data = graphlab.SFrame.read_csv('kc_house_train_data.csv/',column_type_hints=dtype_dict)
test_data = graphlab.SFrame.read_csv('kc_house_test_data.csv/',column_type_hints=dtype_dict)


Finished parsing file /home/srijit/coursera/ml/paper2/kc_house_train_data.csv

Parsing completed. Parsed 100 lines in 0.35401 secs.

Finished parsing file /home/srijit/coursera/ml/paper2/kc_house_train_data.csv

Parsing completed. Parsed 17384 lines in 0.084439 secs.

Finished parsing file /home/srijit/coursera/ml/paper2/kc_house_test_data.csv

Parsing completed. Parsed 100 lines in 0.024208 secs.

Finished parsing file /home/srijit/coursera/ml/paper2/kc_house_test_data.csv

Parsing completed. Parsed 4229 lines in 0.020509 secs.

In [6]:
def simple_linear_regression(input_feature, output):
    lr = lm.LinearRegression()
    lr.fit(input_feature,output)    
    return(lr.intercept_, lr.coef_, lr)


In [40]:
train_y = train_data['price'].to_numpy()
train_x = train_data['sqft_living'].to_numpy().reshape(-1,1)
test_price = test_data['price'].to_numpy()
test_sqft = test_data['sqft_living'].to_numpy().reshape(-1,1)
test_bedrooms = test_data['bedrooms'].to_numpy().reshape(-1,1)

In [8]:
intercept, coeff, lrmodel = simple_linear_regression(train_x, train_y)

In [9]:
def get_regression_predictions(input_feature, intercept, slope):
    predicted_output = intercept + (slope * input_feature)
    return(predicted_output)

In [10]:
get_regression_predictions(2650, intercept, coeff)

array([ 700074.84594751])

In [32]:
predicted_output = intercept + (coeff * train_x)
predicted_output.reshape(1,-1)

array([[ 285595.35169091,  677518.13877709,  169992.22744247, ...,
         384280.94556153,  404018.06433565,  240481.93735006]])

In [34]:
predicted_output_lr = lrmodel.predict(train_x)
rss = np.sum((predicted_output_lr - train_y) ** 2)
rss

1201918354177283.2

In [35]:
def inverse_regression_predictions(output, intercept, slope):
    estimated_input = (output - intercept) / slope
    return(estimated_input)

In [37]:
inverse_regression_predictions(800000, intercept, coeff)

array([ 3004.39624515])

In [41]:
train_x_bedroom = train_data['bedrooms'].to_numpy().reshape(-1,1)

In [42]:
intercept_br, coeff_br, lrmodel_br = simple_linear_regression(train_x_bedroom, train_y)

In [43]:
intercept_sqft, coeff_sqft, lrmodel_sqft = simple_linear_regression(train_x, train_y)

In [45]:
predicted_output_lr_bedroom = lrmodel_br.predict(test_bedrooms)
rss_br = np.sum((predicted_output_lr_bedroom - test_price) ** 2)
rss_br

493364585960301.0

In [46]:
predicted_output_lr_sqft = lrmodel_sqft.predict(test_sqft)
rss_sqft = np.sum((predicted_output_lr_sqft - test_price) ** 2)
rss_sqft

275402933617812.09

In [47]:
rss_sqft > rss_br

False